//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Habrahabr_news.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Habrahabr_news.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Избранные статьи пользователя .
        /// </summary>
        internal static string Favorite_Parser_PrintContent_Избранные_статьи_пользователя_ {
            get {
                return ResourceManager.GetString("Favorite_Parser_PrintContent_Избранные_статьи_пользователя_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на DVolk inc., 2014
        ///dvolk007@mail.ru.
        /// </summary>
        internal static string Form1_AboutToolStripMenuItem_Click_ {
            get {
                return ResourceManager.GetString("Form1_AboutToolStripMenuItem_Click_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Habrahabr News.
        /// </summary>
        internal static string Form1_Form1_Resize_Habrahabr_News {
            get {
                return ResourceManager.GetString("Form1_Form1_Resize_Habrahabr_News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Приложение работает в фоновом режиме!.
        /// </summary>
        internal static string Form1_Form1_Resize_Приложение_работает_в_фоновом_режиме_ {
            get {
                return ResourceManager.GetString("Form1_Form1_Resize_Приложение_работает_в_фоновом_режиме_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Habrahabr News.
        /// </summary>
        internal static string Main_Parser_GetUserAttention_Habrahabr_News {
            get {
                return ResourceManager.GetString("Main_Parser_GetUserAttention_Habrahabr_News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Появились новые статьи!.
        /// </summary>
        internal static string Main_Parser_GetUserAttention_Появились_новые_статьи_ {
            get {
                return ResourceManager.GetString("Main_Parser_GetUserAttention_Появились_новые_статьи_", resourceCulture);
            }
        }
    }
}
